name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest httpx fastapi sqlalchemy pydantic-settings psycopg[binary]
        cd backend && pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/backend
        pylint backend/app --disable=C,R --exit-zero

    - name: Test with pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/backend
        python -m pytest -v backend/tests/
